apiVersion: v1
kind: Service
metadata:
  name: {{ include "alidns-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "alidns-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "alidns-webhook.selectorLabels" . | nindent 4 }}
